# Generated by Django 3.0.4 on 2020-04-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.TextField(verbose_name='Наименование')),
                ('object_value', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('object_priceBuy', models.PositiveIntegerField(verbose_name='Стоимость Покупки')),
                ('object_priceSell', models.PositiveIntegerField(verbose_name='Стоимость Продажи')),
                ('object_date', models.DateField(verbose_name='Дата')),
            ],
        ),
    ]
