# Generated by Django 3.0.4 on 2020-04-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('object_value', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('object_priceBuy', models.PositiveIntegerField(verbose_name='Стоимость Покупки')),
                ('object_priceSell', models.PositiveIntegerField(verbose_name='Стоимость Продажи')),
                ('object_date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.DeleteModel(
            name='object',
        ),
    ]
